# Use Redcarpet for Github like code blocks.
markdown: redcarpet

# Define structure of links to posts
permalink: /blog/:year/:month/:day/:title/

# Exclude everything, that is required for development, from the the page
exclude: [node_modules, package.json, bower_components, bower.json, Gruntfile.js, README.md, LICENSE.txt]
