# Define defaults properties
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

# Define structure of links to posts
permalink: /blog/:year/:month/:day/:title/

# Exclude license and README from generated page
exclude: [README.md, LICENSE]

# Use Redcarpet for support of Github flavored Markdown
markdown: redcarpet
